@echo off
echo Starting FastAPI backend on http://127.0.0.1:8000 ...
start "backend" cmd /k "cd /d %~dp0backend && .venv\Scripts\python -m uvicorn app.main:app --host 127.0.0.1 --port 8000 --reload"
echo Starting React frontend on http://localhost:5173 ...
start "frontend" cmd /k "cd /d %~dp0frontend && npm run dev"